name: qm
description: Locked Async Notifiers for Queries and Mutations
version: 0.2.0
repository: https://github.com/dickermoshe/async_lock
homepage: https://github.com/dickermoshe/async_lock/tree/main/qm

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  locked_async: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "any"

dependency_overrides:
  locked_async:
    path: ../
